# Generated by Django 5.0.7 on 2024-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_alter_status_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Status", "verbose_name_plural": "Statuses"},
        ),
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Created_at"),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
